# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d13848cc99fd76fa663ace639dbda197ad424c670cb8be58c55bc8960a760fa1671b86b0511c9cec83b04b3e66f8a6547cbb854d0a962ebccba6dfc17f7512b

test:
  secret_key_base: 5b22a91618b75e4ab5438ebab7f60c305d4c79fcc7c3d696c06419ba7cd286381d767fb9533263dda7aa7f4c16dbf52aa71916ecb6afd90624f2e86a9835017c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
